apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: linstor-controller-pod-scrape
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: api
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-controller
