apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: linstor-satellite-pod-scrape
spec:
  podMetricsEndpoints:
    - port: prometheus
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-satellite
