{
 "title": "Linstor storage",
 "tags": [
  "linstor",
  "drbd",
  "piraeus",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(linstor_volume_state,node)"
    }
   },
   {
    "name": "storage_pool",
    "label": "pool",
    "query": {
     "query": "label_values(linstor_storage_pool_error_count,storage_pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Space usage in Storage Pool / $storage_pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "storage_pool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(storage_pool)(linstor_storage_pool_capacity_total_bytes{storage_pool=~\"$storage_pool\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(storage_pool)(linstor_storage_pool_capacity_total_bytes{storage_pool=~\"$storage_pool\"})-sum by(storage_pool)(linstor_storage_pool_capacity_free_bytes{storage_pool=~\"$storage_pool\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Volume health / $storage_pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "repeat": "storage_pool",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(linstor_volume_state{storage_pool=~\"$storage_pool\"} == -1) or vector(0)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "count(linstor_volume_state{storage_pool=~\"$storage_pool\"} == 1) or vector(0)",
     "legendFormat": "UpToDate"
    },
    {
     "expr": "count(linstor_volume_state{storage_pool=~\"$storage_pool\"} >=2 <=4) or vector(0)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "(count(linstor_volume_state{storage_pool=~\"$storage_pool\"} >=5 <=6) + count(linstor_volume_state{storage_pool=~\"$storage_pool\"} == 90)) or vector(0)",
     "legendFormat": "Failing"
    },
    {
     "expr": "count(linstor_volume_state{storage_pool=~\"$storage_pool\"} >=7 <=9) or vector(0)",
     "legendFormat": "Transitioning"
    }
   ]
  },
  { "title": "Controller status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg_over_time(linstor_scrape_duration_seconds[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}